import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "./Navbar/page";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"], 
  variable: "--font-poppins", 
});


export const metadata = {
  title: "VibeSync",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}`}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
